# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode8.1
language: objective-c
# cache: cocoapods
# podfile: Example/Podfile
# before_install:
# - gem install cocoapods # Since Travis is not always on latest version
# - pod install --project-directory=Example

#xcode_workspace: Example/gn_api_sdk_ios.xcworkspace
#xcode_scheme: gn_api_sdk_ios-Example
#xcode_sdk: iphonesimulator10.1

script:
#- xcodebuild clean build test -workspace Example/gn_api_sdk_ios.xcworkspace -scheme gn_api_sdk_ios-Example -sdk iphonesimulator10.1 ONLY_ACTIVE_ARCH=NO | xcpretty
- set -o pipefail && xcodebuild clean build test -workspace Example/NuSignUp.xcworkspace -scheme NuSignUp-Example -sdk iphonesimulator9.3 ONLY_ACTIVE_ARCH=NO | xcpretty
- pod lib lint --allow-warnings
